version: "3"
services:
  postgres-cstore:
    image: takahish/postgres-cstore:12.11.2
    container_name: postgres-cstore
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/dwh_user
      POSTGRES_PASSWORD_FILE: /run/secrets/dwh_password
      POSTGRES_DB: dwh
    ports:
      - 5432:5432
    volumes:
      - ./warehouse:/var/lib/postgresql/data
    networks:
      - dwh-network
    secrets:
      - dwh_password
      - dwh_user
  pgadmin:
    image: dpage/pgadmin4:6.11
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.jp
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - dwh-network
    depends_on:
      - postgres-cstore
  metabase:
    image: metabase/metabase:v0.43.4
    container_name: metabase
    hostname: metabase
    volumes:
      - ./metabase:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: dwh
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/dwh_user
      MB_DB_PASS_FILE: /run/secrets/dwh_password
      MB_DB_HOST: postgres-cstore
    networks:
      - dwh-network
    depends_on:
      - postgres-cstore
    secrets:
      - dwh_password
      - dwh_user
networks:
  dwh-network:
    driver: bridge
secrets:
   dwh_password:
     file: sec/dwh_password.txt
   dwh_user:
     file: sec/dwh_user.txt
