version: "3"
services:
  postgres-cstore:
    image: takahish/postgres-cstore:12.11.1
    restart: always
    environment:
      POSTGRES_USER: dwhuser
      POSTGRES_PASSWORD: dwhuser
      POSTGRES_DB: dwhuser
    ports:
      - 5432:5432
    volumes:
      - ./warehouse:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.11
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@cons.jp
      PGADMIN_DEFAULT_PASSWORD: pgadmin
